#obj-$(CONFIG_IL005_USER) += il005.o lib-gpio.o

obj-$(CONFIG_IL005_USER) += il005.o
il005-objs := il005-v.o  \
			  lib-gpio.o  \
			  i2c_sw.o  \
			  il005communication.o  \
			  il005command.o  \
			  il005hal_i2c.o  \
			  timer_util.o \
			  il005test.o \
			  sha256.o
